import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Privacy Policy | Joel Affiliates",
  description: "Privacy Policy for Joel Affiliates — how we collect, use, and protect your personal information.",
};

export default function PrivacyPolicy() {
  return (
    <div className="min-h-screen bg-[#fafaf8]">
      <header className="bg-[#1a2744] text-white py-6">
        <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
          <Link href="/" className="text-sm text-blue-200/60 hover:text-white transition-colors">
            &larr; Back to Home
          </Link>
          <h1 className="mt-4 text-3xl sm:text-4xl font-bold font-[family-name:var(--font-montserrat)]">
            Privacy Policy
          </h1>
          <p className="mt-2 text-blue-200/70 text-sm">Last updated: June 13, 2025</p>
        </div>
      </header>

      <article className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-12">
        <section className="mb-8">
          <h2 className="text-xl font-bold font-[family-name:var(--font-montserrat)] mb-3">1. Introduction</h2>
          <p className="text-[#1a2744]/80 leading-relaxed">
            Welcome to Joel Affiliates (&quot;we,&quot; &quot;our,&quot; or &quot;us&quot;). We respect your privacy and are committed to protecting your personal data. This Privacy Policy explains how we collect, use, disclose, and safeguard your information when you visit our website at affilliate-eta.vercel.app (the &quot;Site&quot;). Please read this Privacy Policy carefully. If you do not agree with the terms of this Privacy Policy, please do not access the Site. We may update this Privacy Policy from time to time, and we will notify you of any changes by posting the new Privacy Policy on this page and updating the &quot;Last updated&quot; date.
          </p>
        </section>

        <section className="mb-8">
          <h2 className="text-xl font-bold font-[family-name:var(--font-montserrat)] mb-3">2. Information We Collect</h2>
          <p className="text-[#1a2744]/80 leading-relaxed mb-3">
            We may collect information about you in a variety of ways. The information we may collect on the Site includes:
          </p>
          <h3 className="font-semibold text-[#1a2744] mb-2">Personal Data</h3>
          <p className="text-[#1a2744]/80 leading-relaxed mb-3">
            Personally identifiable information, such as your name, email address, and other information you voluntarily provide to us when you subscribe to our newsletter, leave a comment, or contact us. We only collect personal information that you voluntarily submit to us. You are under no obligation to provide us with personal information of any kind; however, your refusal to do so may prevent you from using certain features of the Site.
          </p>
          <h3 className="font-semibold text-[#1a2744] mb-2">Non-Personal Data</h3>
          <p className="text-[#1a2744]/80 leading-relaxed mb-3">
            Non-personally identifiable information, including but not limited to your browser type, operating system, IP address, the pages you visit on our Site, the time and date of your visit, the time spent on each page, and other technical information about your device and browsing activity. This information is collected automatically through cookies and similar tracking technologies.
          </p>
          <h3 className="font-semibold text-[#1a2744] mb-2">Google Analytics Data</h3>
          <p className="text-[#1a2744]/80 leading-relaxed">
            We use Google Analytics to collect and analyze website usage data. Google Analytics uses cookies to track user interactions on our Site. The information generated by these cookies about your use of the Site is transmitted to and stored by Google on servers in the United States. Google may use this data to contextualize and personalize the ads served on its advertising network. For more information about how Google uses your data, please visit Google&apos;s Privacy and Terms page. You can opt out of Google Analytics tracking by installing the Google Analytics opt-out browser add-on.
          </p>
        </section>

        <section className="mb-8">
          <h2 className="text-xl font-bold font-[family-name:var(--font-montserrat)] mb-3">3. How We Use Your Information</h2>
          <p className="text-[#1a2744]/80 leading-relaxed mb-3">
            We may use the information we collect about you for various purposes, including to:
          </p>
          <ul className="list-disc list-inside text-[#1a2744]/80 leading-relaxed space-y-1">
            <li>Send you newsletters, marketing communications, and promotional content (only with your consent)</li>
            <li>Respond to your comments, questions, and requests</li>
            <li>Analyze how the Site is used to improve content and user experience</li>
            <li>Monitor and analyze usage and trends to improve your experience with our Site</li>
            <li>Track affiliate link clicks to attribute sales and commissions correctly</li>
            <li>Detect, prevent, and address technical issues and security threats</li>
            <li>Comply with legal obligations and enforce our terms of service</li>
          </ul>
        </section>

        <section className="mb-8">
          <h2 className="text-xl font-bold font-[family-name:var(--font-montserrat)] mb-3">4. Sharing Your Information</h2>
          <p className="text-[#1a2744]/80 leading-relaxed mb-3">
            We do not sell, trade, or rent your personal identification information to others. We may share generic aggregated demographic information not linked to any personal identification information with our affiliate network partners and advertisers for the purposes outlined above. We may also share your information when we believe release is appropriate to comply with the law, enforce our site policies, or protect ours or others&apos; rights, property, or safety.
          </p>
          <p className="text-[#1a2744]/80 leading-relaxed">
            When you click on an affiliate link on our Site, you may be directed to a third-party website. These third-party sites have their own privacy policies, and we are not responsible for the practices of these sites. We encourage you to read the privacy policies of every website you visit. Affiliate links on our Site may use tracking cookies set by the respective affiliate networks (Amazon, ShareASale, ClickBank, Shopify) to track referrals and attribute commissions.
          </p>
        </section>

        <section className="mb-8">
          <h2 className="text-xl font-bold font-[family-name:var(--font-montserrat)] mb-3">5. Cookies and Tracking Technologies</h2>
          <p className="text-[#1a2744]/80 leading-relaxed mb-3">
            We use cookies and similar tracking technologies to track activity on our Site and hold certain information. Cookies are files with small amounts of data which may include an anonymous unique identifier. You can instruct your browser to refuse all cookies or to indicate when a cookie is being sent. However, if you do not accept cookies, you may not be able to use some portions of our Site. The cookies used on our Site include:
          </p>
          <ul className="list-disc list-inside text-[#1a2744]/80 leading-relaxed space-y-1">
            <li>Essential cookies — necessary for the Site to function properly</li>
            <li>Analytics cookies — used by Google Analytics to understand how visitors interact with the Site</li>
            <li>Affiliate cookies — set by affiliate networks when you click on affiliate links (e.g., Amazon&apos;s 24-hour cookie, ShareASale&apos;s 30-day cookie)</li>
          </ul>
        </section>

        <section className="mb-8">
          <h2 className="text-xl font-bold font-[family-name:var(--font-montserrat)] mb-3">6. Data Security</h2>
          <p className="text-[#1a2744]/80 leading-relaxed">
            We adopt appropriate data collection, storage, and processing practices and security measures to protect against unauthorized access, alteration, disclosure, or destruction of your personal information. However, no method of transmission over the Internet or method of electronic storage is 100% secure. Therefore, we cannot guarantee its absolute security. We use HTTPS encryption across our entire Site to ensure your data is transmitted securely.
          </p>
        </section>

        <section className="mb-8">
          <h2 className="text-xl font-bold font-[family-name:var(--font-montserrat)] mb-3">7. Your Rights</h2>
          <p className="text-[#1a2744]/80 leading-relaxed mb-3">
            Depending on your location, you may have the following rights regarding your personal data:
          </p>
          <ul className="list-disc list-inside text-[#1a2744]/80 leading-relaxed space-y-1">
            <li>The right to access — you can request copies of your personal data</li>
            <li>The right to rectification — you can request correction of inaccurate data</li>
            <li>The right to erasure — you can request deletion of your personal data</li>
            <li>The right to restrict processing — you can request limitation of data processing</li>
            <li>The right to data portability — you can request transfer of your data</li>
            <li>The right to object — you can object to our processing of your personal data</li>
          </ul>
          <p className="text-[#1a2744]/80 leading-relaxed mt-3">
            To exercise any of these rights, please contact us using the information provided below. We will respond to your request within 30 days.
          </p>
        </section>

        <section className="mb-8">
          <h2 className="text-xl font-bold font-[family-name:var(--font-montserrat)] mb-3">8. Children&apos;s Privacy</h2>
          <p className="text-[#1a2744]/80 leading-relaxed">
            Our Site is not intended for children under the age of 13. We do not knowingly collect personal information from children under 13. If we become aware that we have collected personal information from a child under 13 without verification of parental consent, we will take steps to remove that information from our servers. If you are a parent or guardian and you believe your child has provided us with personal information, please contact us.
          </p>
        </section>

        <section className="mb-8">
          <h2 className="text-xl font-bold font-[family-name:var(--font-montserrat)] mb-3">9. Contact Us</h2>
          <p className="text-[#1a2744]/80 leading-relaxed">
            If you have any questions about this Privacy Policy, please contact us at: Joel Ssengendo, Email: joelssengendo1204@gmail.com, Website: affilliate-eta.vercel.app. We will do our best to respond to your inquiry within a reasonable timeframe.
          </p>
        </section>
      </article>
    </div>
  );
}
